- name: "Copy Fuseki compacting into place"
  template:
    src: fuseki-compact.unit.j2
    dest: /etc/systemd/system/fuseki-compact.service

- name: "Copy Fuseki compacting Timer into place"
  template:
    src: "fuseki-compact.timer.j2"
    dest: "/etc/systemd/system/fuseki-compact.timer"

- name: "Enable fuseki compacting timer"
  systemd:
    daemon_reload: "yes"
    name: "fuseki-compact.timer"
    state: started

- name: "Add fuseki start for {{ fuseki_user }} to sudoers file"
  lineinfile:
    path: /etc/sudoers
    line: "{{ item }}"
    validate: '/usr/sbin/visudo -cf %s'
  with_items:
  - "{{ fuseki_user }} ALL=(ALL) NOPASSWD: /usr/bin/systemctl start fuseki.service"
