---
- name: fuseki present
  command: "echo fuseki"
  register: fuseki_present
  when: "'apache-jena-fuseki' in fuseki_components"
    
- name: Ensure fuseki_user group exists.
  group:
    name: "{{ fuseki_user }}"
    state: present
  when: fuseki_create_user
  become: true

- name: Ensure fuseki_user exists.
  user:
    name: "{{ fuseki_user }}"
    group: "{{ fuseki_user }}"
    system: yes
    state: present
  when: fuseki_create_user
  become: true

- name: Check if Fuseki and Jena have been installed already.
  stat:
    path: "{{ fuseki_install_dir }}/{{ item }}-{{ fuseki_version }}"
  with_items: "{{ fuseki_components }}"
  register: fuseki_install_status

- name: Download Fuseki and Jena.
  get_url:
    url: "{{ fuseki_mirror }}/jena/binaries/{{ item.item }}-{{ fuseki_version }}.tar.gz"
    dest: "{{ fuseki_workspace }}/{{ item.item }}-{{fuseki_version }}.tar.gz"
    force: no
  with_items: "{{ fuseki_install_status.results }}"
  when: item.stat.isdir is not defined
  register: fuseki_download_status
  become: true

- name: Expand Fuseki and Jena.
  unarchive:
    src: "{{ fuseki_workspace }}/{{ item.item.item }}-{{fuseki_version }}.tar.gz"
    dest: "{{ fuseki_install_dir }}"
    copy: no
  with_items: "{{ fuseki_download_status.results }}"
  when: item.changed == true
  become: true

- name: Create symlink to unnumbered apache jena and fuseki
  file:
    src: "{{fuseki_install_dir}}/{{ item }}-{{ fuseki_version }}"
    dest: "/opt/{{ item | replace('apache-','') | replace('jena-fuseki','fuseki')}}"
    state: link
    owner: "{{fuseki_user}}"
    group: "{{fuseki_user}}"
  become: true
  with_items: "{{fuseki_components}}"

- name: Delete Fuseki and Jena downloads.
  file:
    path: "{{ fuseki_workspace }}/{{ item }}-{{fuseki_version }}.tar.gz"
    state: absent
  with_items: "{{ fuseki_components }}"
  become: true

- name: set up and configure fuseki
  block:
  - name: "Configure environment ($PATH)."
    template:
      src: "env.sh.j2"
      dest: "/etc/profile.d/fuseki.sh"

  - name: Configure Fuseki defaults.
    template:
      src: "fuseki-defaults.j2"
      dest: "/etc/default/fuseki"

  - name: "Ensure that $FUSEKI_BASE, and subdirs configuration and databases exists."
    file:
      path: "{{ item }}"
      owner: "{{ fuseki_user }}"
      group: "{{ fuseki_user }}"
      mode: 0770
      state: directory
    with_items:
      - "{{ fuseki_base }}"
      - "{{ fuseki_base }}/configuration"
      - "{{ fuseki_base }}/databases"

  - name: "Configure Fuseki"
    template:
      src: "fuseki-config.ttl.j2"
      dest: "{{ fuseki_base }}/configuration/{{ item.name }}.ttl"
      owner: "{{ fuseki_user }}"
      group: "{{ fuseki_user }}"
      mode: 0660
    with_items: "{{ fuseki_configurations }}"

  - name: "Copy Fuseki systemd unit file into place (template from jena-fuseki)"
    template:
      src: fuseki.unit.j2
      dest: /etc/systemd/system/fuseki.service
      owner: root
      group: root
      mode: 0755

  - name: "Ensure Fuseki is started and enabled on boot if configured"
    service:
      name: "fuseki"
      state: "{{ fuseki_service_state }}"
      enabled: yes
    when: fuseki_service_manage
    notify: fuseki restart
  when: "fuseki_present.stout == 'fuseki'"
  become: true

