- name: "comment out normal startup"
  lineinfile:
    path: "{{ fuseki_home }}/fuseki-server"
    regexp: "^(exec \\$JAVA \\$JVM_ARGS -jar.+)" 
    line: "#\\1"

- name: "Update fuseki-server to add library modules"
  lineinfile:
    path: "{{ fuseki_home }}/fuseki-server"
    line: "java $JVM_ARGS -cp \"$JAR:$FUSEKI_EXTRA\" org.apache.jena.fuseki.cmd.FusekiCmd \"$@\""
    state: "present"

- name: "Download modules to $JENA_HOME/lib"
  get_url:
    url: "{{ item }}"
    dest: "{{ fuseki_home }}/lib/"
  with_items: "{{ fuseki_modules }}"
  when: "fuseki_modules | length > 0"
